#!/bin/bash

echo "🔧 Hướng dẫn lấy Gemini API Key"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📌 Bước 1: Mở trình duyệt"
echo "   → https://aistudio.google.com/app/apikey"
echo ""
echo "📌 Bước 2: Đăng nhập Google Account"
echo ""
echo "📌 Bước 3: Click 'Create API key' hoặc 'Get API key'"
echo ""
echo "📌 Bước 4: Chọn project '748600758533' (cùng project hiện tại)"
echo ""
echo "📌 Bước 5: Copy API key (format: AIzaSyXXXXXXXXX...)"
echo ""
echo "📌 Bước 6: Paste vào .env.local"
echo "   Mở file:"
echo "   $ nano .env.local"
echo ""
echo "   Tìm dòng:"
echo "   # GEMINI_API_KEY=AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo ""
echo "   Uncomment và paste key:"
echo "   GEMINI_API_KEY=AIzaSy_YOUR_REAL_KEY_HERE"
echo ""
echo "📌 Bước 7: Restart server"
echo "   $ npm run dev"
echo ""
echo "📌 Bước 8: Test"
echo "   $ node test-moderation.js"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "⚠️  HIỆN TẠI: Hệ thống đang dùng RULE-BASED moderation"
echo "✅  Rule-based vẫn hoạt động 100% (không cần API key)"
echo "🚀  Thêm Gemini key để tăng độ chính xác!"
echo ""
