#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "  🚨 KEY THỨ 3 CŨNG KHÔNG HOẠT ĐỘNG!"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Bạn đã thử 3 lần, tất cả đều từ Cloud Console:"
echo ""
echo "  ❌ Key 1: AQ.Ab8RN6JL83J... (project 748600758533)"
echo "  ❌ Key 2: AQ.Ab8RN6lpAXz... (project 93505035428)"
echo "  ❌ Key 3: AQ.Ab8RN6JcmfF... (project pulo-app-507117) ← MỚI NHẤT"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🔍 VẤN ĐỀ: Bạn đang tạo key ở CLOUD CONSOLE!"
echo ""
echo "   Trang bạn đang dùng:"
echo "   ❌ https://console.cloud.google.com/apis/credentials"
echo ""
echo "   Trang cần dùng:"
echo "   ✅ https://aistudio.google.com/app/apikey"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📌 MỞ ĐÚNG TRANG NGAY BÂY GIỜ:"
echo ""
echo "   Cách 1: Copy link này và paste vào browser"
echo "   👉 https://aistudio.google.com/app/apikey"
echo ""
echo "   Cách 2: Chạy lệnh này (macOS)"

if [[ "$OSTYPE" == "darwin"* ]]; then
  echo "   👉 open 'https://aistudio.google.com/app/apikey'"
  echo ""
  read -p "   Bấm ENTER để mở AI Studio trong browser: " 
  open "https://aistudio.google.com/app/apikey"
  echo ""
  echo "   ✅ Đã mở AI Studio!"
  echo ""
else
  echo "   👉 xdg-open 'https://aistudio.google.com/app/apikey'"
  echo ""
fi

echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📋 CHECKLIST (làm theo từng bước):"
echo ""
echo "   □ Trang vừa mở có tiêu đề 'Google AI Studio'?"
echo "   □ URL là aistudio.google.com (KHÔNG phải console.cloud...)?"
echo "   □ Có nút màu xanh 'Get API key' hoặc 'Create API key'?"
echo "   □ Click vào nút đó"
echo "   □ Chọn project 'pulo-app-507117' hoặc tạo mới"
echo "   □ Copy key (bắt đầu bằng AIzaSy...)"
echo "   □ Key có 39 ký tự?"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "💡 CÁCH NHẬN BIẾT KEY ĐÚNG:"
echo ""
echo "   ✅ Key đúng: AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo "   ❌ Key sai:  AQ.Ab8RN6XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
echo ""
echo "   → Nếu bắt đầu AQ. → SAI, đóng lại và vào AI Studio!"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
