#!/bin/bash
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "🔍 Checking macOS Camera/Mic Permissions"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ STEP 1: Run this command to open System Settings:"
echo "   open 'x-apple.systempreferences:com.apple.preference.security?Privacy_Camera'"
echo ""
echo "✅ STEP 2: In System Settings:"
echo "   • Go to Privacy & Security → Camera"
echo "   • Find 'Google Chrome' and CHECK it"
echo "   • Go to Privacy & Security → Microphone"  
echo "   • Find 'Google Chrome' and CHECK it"
echo ""
echo "✅ STEP 3: Restart Chrome:"
echo "   killall 'Google Chrome'"
echo ""
echo "✅ STEP 4: Reopen Chrome and test in Console (F12):"
echo ""
echo "navigator.mediaDevices.getUserMedia({ video: true, audio: true })"
echo "  .then(s => { console.log('✅ SUCCESS'); s.getTracks().forEach(t => t.stop()); })"
echo "  .catch(e => console.error('❌', e.name));"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
